# Generated by Django 3.0.8 on 2020-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtrends',
            name='image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
