# Generated by Django 3.0.8 on 2020-07-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_newtrends_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bracelets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='neckless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='featuredproducts',
            name='image',
            field=models.FileField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newtrends',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
