# Generated by Django 3.0.8 on 2020-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200711_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='earingsdatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='jewellarydatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
    ]
