# Generated by Django 3.0.8 on 2020-07-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_earingsdatabase_jewellarydatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='braceletsdatabase',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earingsdatabase',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredproducts',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewellarydatabase',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necklessdatabase',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newtrends',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ringsdatabase',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
