# Generated by Django 3.0.8 on 2020-07-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200712_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewdatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('star', models.IntegerField()),
                ('code', models.IntegerField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
