# Generated by Django 3.0.8 on 2020-07-16 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200716_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 5, 45, 47, 519862, tzinfo=utc)),
        ),
    ]
