# Generated by Django 3.0.8 on 2020-07-16 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200716_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='braceletsdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 329855, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='earingsdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 330697, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='featuredproducts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 328623, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='jewellarydatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 330237, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='necklessdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 329458, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='newtrends',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 328175, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ringsdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 329030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviewdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 11, 35, 49, 331508, tzinfo=utc)),
        ),
    ]
