# Generated by Django 3.0.8 on 2020-07-16 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200716_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newtrends',
        ),
        migrations.AlterField(
            model_name='braceletsdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 19, 104509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='braceletsdatabase',
            name='type',
            field=models.CharField(default='bracelet', max_length=20),
        ),
        migrations.AlterField(
            model_name='earingsdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 19, 105344, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='earingsdatabase',
            name='type',
            field=models.CharField(default='earing', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 19, 103158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jewellarydatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 19, 104934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jewellarydatabase',
            name='type',
            field=models.CharField(default='jewellery', max_length=20),
        ),
        migrations.AlterField(
            model_name='necklessdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 19, 104106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='necklessdatabase',
            name='type',
            field=models.CharField(default='necklace', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 19, 106209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ringsdatabase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 19, 103672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ringsdatabase',
            name='type',
            field=models.CharField(default='ring', max_length=20),
        ),
    ]
