# Generated by Django 3.0.8 on 2020-07-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200717_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necklessdatabase',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
